### ISSUE TITLE
Susi tweetbot is not working.

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_tweetbot#6]
susi_tweetbot is not working. 

I tried tweeting to it and got no replies, which can be seen here:
<img width="441" alt="susi_tweetbotfinalpng" src="https://user-images.githubusercontent.com/20307535/27214345-87abde1a-5289-11e7-8431-07329d8bc42e.PNG">

Would you like to work on this issue?
Yes.

**Comment by mariobehling** [comment]
I guess it is a set up issue. The bot is not set up and we don't have access to the susi_tweetbot account.

@hoangvanthien Could you share the account login please by email?

**Comment by hoangvanthien** [comment]
The bot only works if the code is executed/run. And sorry, I don't have a machine/server that runs 24/7 to maintain the bot alive. If anyone want to test it, change the Twitter Token and run the code locally in need.

**Comment by hoangvanthien** [comment]
Anyway, I have sent the login password to @hpdang for further improvement.
